description: Build program


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''

  branch:
    description: platform
    required: false
    default: ''

  arch:
    description: platform
    required: false
    default: 'x64'



runs:
  using: composite

  steps:

  - uses: fu1ny2t-3es/gi1-ac2io3s@checkout-branch
    with:
      branch: ${{ inputs.branch }}

      token: ${{ inputs.token }}
      auto: true


  - if: inputs.arch == 'x86' || inputs.arch == 'x64'
    uses: fu1ny2t-3es/gi1-ac2io3s@mingw-install
    with:
      arch: ${{ inputs.arch }}



  - if: inputs.arch == 'so64'
    name: Install deps
    working-directory: ${{ github.workspace }}
    shell: bash
    run: |
      ./.github/actions/install_deps.sh ubuntu-latest
      make -j bootroms BOOTROMS_DIR="${{ github.workspace }}/build/bin/BootROMs"



  - if: inputs.arch == 'x86' || inputs.arch == 'x64'
    working-directory: ${{ github.workspace }}/libretro
    env:
      CC: ${{ env.MINGW_CC }}
      CXX: ${{ env.MINGW_CXX }}
    shell: pwsh
    run: |
      curl --no-progress-meter -L -o bootrom.zip "https://github.com/fu1ny2t-3es/sa1eb2y/archive/refs/heads/bootrom.zip"
      unzip -j bootrom.zip | Out-Null

      make platform="win" BOOTROMS_DIR="${{ github.workspace }}\libretro"



  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}/libretro
    env:
      CC: gcc
      CXX: g++
    shell: bash
    run: |
      make platform="unix" BOOTROMS_DIR="${{ github.workspace }}/build/bin/BootROMs"
      mv ../*_boot.c .
      cp *_boot.c ../..



  - if: inputs.arch == 'so64'
    uses: fu1ny2t-3es/gi1-ac2io3s@checkout-repo
    with:
      repository: fu1ny2t-3es/sa1eb2y
      token: ${{ inputs.token }}
      auto: true



  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    shell: bash
    run: |
      git checkout --orphan cache-temp-report
      git reset --hard
      mv ../*_boot.c .



  - if: inputs.arch == 'so64'
    working-directory: ${{ github.workspace }}
    shell: bash
    run: |
      flag=0

      archive() {
        if test -f $1; then
          git add $1
          flag=1
        fi
      }


      archive "agb_boot.c"
      archive "cgb0_boot.c"
      archive "cgb_boot.c"
      archive "dmg_boot.c"
      archive "mgb_boot.c"
      archive "sgb_boot.c"
      archive "sgb2_boot.c"


      if (( $flag == 1 )); then
        git commit -m "[cache] bootrom"
        git push -f --set-upstream origin HEAD:bootrom
      fi



  - uses: actions/upload-artifact@main
    with:
      name: SameBoy_${{ inputs.arch }}
      path: |
        ${{ github.workspace }}/**.dll
        ${{ github.workspace }}/**.so
