on:
  push:
  workflow_dispatch:


jobs:

  build:
    strategy:
      matrix:
        arch: [so64, x86, x64]
      fail-fast: false


    runs-on: ubuntu-latest


    steps:

    - uses: fu1ny2t-3es/sa1eb2y@build
      with:
        branch: upstream
        arch: ${{ matrix.arch }}

        token: ${{ secrets.token }}
