on:
  workflow_dispatch:
  schedule:
    - cron: '45 4 */6 * *'


jobs:

  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: fu1ny2t-3es/sa1eb2y@cron
        with:
          token: ${{ secrets.token }}
